#!/usr/bin/env python3
"""Build a reduced CC-CEDICT subset for Quick Look fallback experiments.

This tooling-only script reads a full CC-CEDICT SQLite database generated by
convert_cc_cedict_sample.py and writes a smaller candidate database in /tmp.
It does not modify or integrate with the iOS app target.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
import unicodedata
from dataclasses import asdict, dataclass
from pathlib import Path


LICENSE_SOURCE = "CC-CEDICT CC BY-SA 4.0"

CHINESE_SEEDS = [
    "购物",
    "购物金",
    "购物车",
    "充值",
    "支付",
    "付款",
    "订单",
    "退款",
    "退货",
    "发货",
    "快递",
    "物流",
    "运输",
    "国际运输",
    "运费",
    "仓库",
    "仓",
    "入仓",
    "包装",
    "箱子",
    "外箱",
    "标签",
    "货物",
    "木架",
    "优惠",
    "优惠券",
    "折扣",
    "价格",
    "价",
    "元",
    "件",
    "数量",
    "颜色",
    "尺码",
    "尺寸",
    "材料",
    "材质",
    "规格",
    "卖家",
    "买家",
    "客服",
    "联系",
    "消息",
    "地址",
    "收货",
    "确认",
    "取消",
    "保存",
    "删除",
    "搜索",
    "外卖",
    "现货",
    "秒发",
    "专柜",
    "新版",
    "功能",
    "多功能",
    "洗面奶",
    "化妆水",
    "护肤",
    "发酵",
    "导入",
    "鞋",
    "高跟鞋",
    "衣服",
    "裤",
    "裙",
    "包",
    "手机",
    "电脑",
    "家具",
]

ENGLISH_SEEDS = [
    "shop",
    "shopping",
    "cart",
    "pay",
    "payment",
    "order",
    "refund",
    "return",
    "ship",
    "shipping",
    "deliver",
    "delivery",
    "express",
    "takeout",
    "home delivery",
    "logistics",
    "transport",
    "warehouse",
    "packaging",
    "package",
    "box",
    "label",
    "goods",
    "cargo",
    "freight",
    "discount",
    "coupon",
    "price",
    "color",
    "size",
    "material",
    "specification",
    "seller",
    "buyer",
    "customer service",
    "address",
    "receive",
    "confirm",
    "cancel",
    "save",
    "delete",
    "search",
    "stock",
    "in stock",
    "merchandise",
    "recharge",
    "top up",
    "multifunctional",
    "counter",
    "edition",
    "version",
    "toner",
    "lotion",
    "cleansing",
    "cosmetics",
    "skincare",
    "ferment",
    "steam",
    "serum",
    "shoe",
    "shoes",
    "clothes",
    "pants",
    "skirt",
    "bag",
    "phone",
    "computer",
    "furniture",
]

ALLOWLIST = {
    "高跟鞋",
    "仓库",
    "包装",
    "标签",
    "货物",
    "运输",
    "地址",
    "支付",
    "发货",
    "优惠券",
    "退款",
    "外卖",
    "现货",
    "专柜",
    "新版",
    "洗面奶",
    "化妆水",
    "发酵",
    "导入",
    "运费",
    "充值",
    "膨胀",
    "多功能",
}

SINGLE_CHARACTER_ALLOWLIST = {
    "元",
    "件",
}

BLOCKLIST = {
    "点",
    "的",
    "了",
    "在",
    "是",
    "有",
    "和",
    "与",
    "及",
    "或",
    "不",
    "就",
    "都",
    "很",
    "也",
    "又",
    "被",
    "把",
}

NOISY_ENGLISH_FRAGMENTS = [
    "(bound form)",
    "(literary)",
    "(dialect)",
    "classifier",
    "surname",
    "variant of",
    "archaic",
    "modal particle",
    "grammatical particle",
    "interjection",
    "onomatopoeia",
    "phonetic",
    "used in",
    "abbr. for",
    "see also",
    "see ",
    "radical",
]


@dataclass(frozen=True)
class SourceEntry:
    simplified: str
    traditional: str
    source_compact: str
    pinyin: str
    english: str


@dataclass(frozen=True)
class SelectedEntry:
    simplified: str
    traditional: str
    source_compact: str
    pinyin: str
    english: str
    priority: int
    selection_reason: str


@dataclass
class Metrics:
    full_input_rows: int = 0
    reduced_output_rows: int = 0
    selected_by_chinese_seed: int = 0
    selected_by_english_seed: int = 0
    selected_by_allowlist: int = 0
    rejected_by_blocklist: int = 0
    rejected_by_noise_rules: int = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a reduced CC-CEDICT SQLite subset for ScreenTranslator "
            "Quick Look fallback experiments."
        )
    )
    parser.add_argument(
        "--input",
        required=True,
        type=Path,
        help="Full CC-CEDICT SQLite DB generated by convert_cc_cedict_sample.py.",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Reduced SQLite output path, preferably under /tmp.",
    )
    parser.add_argument(
        "--json-output",
        type=Path,
        help="Optional JSON output path for inspecting selected entries.",
    )
    parser.add_argument(
        "--max-english-length",
        type=int,
        default=160,
        help="Reject non-allowlisted English definitions longer than this.",
    )
    parser.add_argument(
        "--max-definition-count",
        type=int,
        default=4,
        help="Reject non-allowlisted entries with more semicolon-separated senses.",
    )
    return parser.parse_args()


def normalized_source(text: str) -> str:
    normalized = unicodedata.normalize("NFKC", text or "")
    invisible = {
        "\u200b",
        "\u200c",
        "\u200d",
        "\u2060",
        "\ufeff",
    }
    return "".join(
        character
        for character in normalized
        if character not in invisible and not character.isspace()
    )


def load_entries(input_path: Path) -> list[SourceEntry]:
    connection = sqlite3.connect(input_path)
    connection.row_factory = sqlite3.Row

    try:
        rows = connection.execute(
            """
            SELECT simplified, traditional, sourceCompact, pinyin, english
            FROM entries
            ORDER BY id
            """
        ).fetchall()
    finally:
        connection.close()

    return [
        SourceEntry(
            simplified=row["simplified"],
            traditional=row["traditional"],
            source_compact=row["sourceCompact"],
            pinyin=row["pinyin"],
            english=row["english"],
        )
        for row in rows
    ]


def matching_chinese_seeds(entry: SourceEntry) -> list[str]:
    candidates = {
        normalized_source(entry.simplified),
        normalized_source(entry.traditional),
        normalized_source(entry.source_compact),
    }
    matches: list[str] = []

    for seed in CHINESE_SEEDS:
        normalized_seed = normalized_source(seed)

        if any(
            normalized_seed in candidate or candidate in normalized_seed
            for candidate in candidates
            if candidate
        ):
            matches.append(seed)

    return sorted(set(matches), key=lambda item: (-len(item), item))


def matching_english_seeds(entry: SourceEntry) -> list[str]:
    english = entry.english.lower()
    matches: list[str] = []

    for seed in ENGLISH_SEEDS:
        pattern = r"(?<![a-z])" + re.escape(seed.lower()) + r"(?![a-z])"

        if re.search(pattern, english):
            matches.append(seed)

    return sorted(set(matches))


def is_blocklisted(entry: SourceEntry) -> bool:
    terms = {
        normalized_source(entry.simplified),
        normalized_source(entry.traditional),
        normalized_source(entry.source_compact),
    }
    return any(term in BLOCKLIST for term in terms)


def is_allowlisted(entry: SourceEntry) -> bool:
    terms = {
        normalized_source(entry.simplified),
        normalized_source(entry.traditional),
        normalized_source(entry.source_compact),
    }
    return any(term in ALLOWLIST for term in terms)


def is_single_character_noise(entry: SourceEntry) -> bool:
    source = normalized_source(entry.source_compact or entry.simplified)
    return len(source) == 1 and source not in SINGLE_CHARACTER_ALLOWLIST


def definition_count(entry: SourceEntry) -> int:
    return len([part for part in entry.english.split(";") if part.strip()])


def is_noisy_entry(
    entry: SourceEntry,
    max_english_length: int,
    max_definition_count: int,
) -> bool:
    if is_allowlisted(entry):
        return False

    if is_single_character_noise(entry):
        return True

    if len(entry.english) > max_english_length:
        return True

    if definition_count(entry) > max_definition_count:
        return True

    lowercased = entry.english.lower()
    return any(fragment in lowercased for fragment in NOISY_ENGLISH_FRAGMENTS)


def select_entry(
    entry: SourceEntry,
    metrics: Metrics,
    max_english_length: int,
    max_definition_count: int,
) -> SelectedEntry | None:
    allowlisted = is_allowlisted(entry)

    if is_blocklisted(entry):
        metrics.rejected_by_blocklist += 1
        return None

    if is_noisy_entry(entry, max_english_length, max_definition_count):
        metrics.rejected_by_noise_rules += 1
        return None

    chinese_matches = matching_chinese_seeds(entry)
    english_matches = matching_english_seeds(entry)

    if not allowlisted and not chinese_matches and not english_matches:
        return None

    reasons: list[str] = []
    priority = 0

    if allowlisted:
        metrics.selected_by_allowlist += 1
        reasons.append("allowlist")
        priority += 100

    if chinese_matches:
        metrics.selected_by_chinese_seed += 1
        reasons.append("chinese:" + "|".join(chinese_matches[:3]))
        priority += 50 + min(30, max(len(match) for match in chinese_matches) * 3)

    if english_matches:
        metrics.selected_by_english_seed += 1
        reasons.append("english:" + "|".join(english_matches[:3]))
        priority += 25 + min(20, len(english_matches) * 2)

    source_length = len(normalized_source(entry.source_compact or entry.simplified))
    priority += min(20, source_length * 2)
    priority -= min(20, max(0, definition_count(entry) - 1) * 3)

    return SelectedEntry(
        simplified=entry.simplified,
        traditional=entry.traditional,
        source_compact=entry.source_compact,
        pinyin=entry.pinyin,
        english=entry.english,
        priority=priority,
        selection_reason=", ".join(reasons),
    )


def create_database(output_path: Path, entries: list[SelectedEntry]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if output_path.exists():
        output_path.unlink()

    connection = sqlite3.connect(output_path)

    try:
        connection.executescript(
            """
            CREATE TABLE entries (
                id INTEGER PRIMARY KEY,
                simplified TEXT,
                traditional TEXT,
                sourceCompact TEXT,
                pinyin TEXT,
                english TEXT,
                sourceKind TEXT,
                licenseSource TEXT,
                priority INTEGER,
                selectionReason TEXT
            );

            CREATE INDEX idx_entries_simplified ON entries(simplified);
            CREATE INDEX idx_entries_traditional ON entries(traditional);
            CREATE INDEX idx_entries_sourceCompact ON entries(sourceCompact);
            CREATE INDEX idx_entries_priority ON entries(priority);
            """
        )
        connection.executemany(
            """
            INSERT INTO entries (
                simplified,
                traditional,
                sourceCompact,
                pinyin,
                english,
                sourceKind,
                licenseSource,
                priority,
                selectionReason
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    entry.simplified,
                    entry.traditional,
                    entry.source_compact,
                    entry.pinyin,
                    entry.english,
                    "cc_cedict",
                    LICENSE_SOURCE,
                    entry.priority,
                    entry.selection_reason,
                )
                for entry in entries
            ],
        )
        connection.commit()
    finally:
        connection.close()


def write_json(output_path: Path, entries: list[SelectedEntry]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(
            [
                {
                    **asdict(entry),
                    "sourceKind": "cc_cedict",
                    "licenseSource": LICENSE_SOURCE,
                }
                for entry in entries
            ],
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


def print_metrics(
    input_path: Path,
    output_path: Path,
    metrics: Metrics,
) -> None:
    output_size = output_path.stat().st_size if output_path.exists() else 0

    print(f"Input: {input_path}")
    print(f"Output: {output_path}")
    print(f"Full input rows: {metrics.full_input_rows}")
    print(f"Reduced output rows: {metrics.reduced_output_rows}")
    print(f"Output SQLite bytes: {output_size}")
    print(f"Selected by Chinese seed: {metrics.selected_by_chinese_seed}")
    print(f"Selected by English seed: {metrics.selected_by_english_seed}")
    print(f"Selected by allowlist: {metrics.selected_by_allowlist}")
    print(f"Rejected by blocklist: {metrics.rejected_by_blocklist}")
    print(f"Rejected by noise rules: {metrics.rejected_by_noise_rules}")


def main() -> int:
    args = parse_args()

    if not args.input.is_file():
        print(f"Input DB not found: {args.input}", file=sys.stderr)
        return 2

    source_entries = load_entries(args.input)
    metrics = Metrics(full_input_rows=len(source_entries))
    selected: list[SelectedEntry] = []

    for source_entry in source_entries:
        selected_entry = select_entry(
            source_entry,
            metrics,
            max_english_length=args.max_english_length,
            max_definition_count=args.max_definition_count,
        )

        if selected_entry is not None:
            selected.append(selected_entry)

    selected.sort(
        key=lambda entry: (
            -entry.priority,
            -len(normalized_source(entry.source_compact or entry.simplified)),
            entry.simplified,
        )
    )
    metrics.reduced_output_rows = len(selected)

    create_database(args.output, selected)

    if args.json_output is not None:
        write_json(args.json_output, selected)

    print_metrics(args.input, args.output, metrics)

    if args.json_output is not None:
        print(f"JSON output: {args.json_output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
