#!/usr/bin/env python3
"""Simulate the future Quick Look Chinese-to-English lookup pipeline.

This tooling-only proof of concept tests phrase-level app UI rules first,
then CC-CEDICT exact lookup, then CC-CEDICT segment lookup. It does not modify
or integrate with the iOS app.
"""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import time
import unicodedata
from dataclasses import asdict, dataclass
from pathlib import Path


MAX_DISPLAY_LABEL_LENGTH = 28

DEFAULT_OCR_PHRASES = [
    "每个箱子外面都必须贴上明显标签",
    "如果可以，请在外箱上注明里面是什么货物，方便仓库识别",
    "这批货物后续还有国际运输，请务必做好非常牢固的包装",
    "打出口加收木架80一个包装费",
    "私人仓，无入仓费",
    "轻熟绝美高跟鞋",
    "购物车",
    "优惠券",
    "退款",
    "仓库",
    "标签",
    "货物",
    "运输",
]

PHRASE_OVERRIDES = {
    "对方正在输入": "typing...",
    "暂无数据": "no data",
    "暂无消息": "no messages",
    "暂无内容": "no content",
    "地铁路线": "metro route",
    "退出登录": "log out",
    "输入验证码": "verification code",
    "绑定手机号": "bind phone",
    "解绑手机号": "unbind phone",
    "退款处理中": "refund processing",
    "快递已发货": "shipped",
    "物流已发货": "shipped",
    "订单已取消": "order canceled",
    "支付失败": "payment failed",
    "支付成功": "payment successful",
    "网络错误请重试": "network error · retry",
    "打开设置": "open settings",
    "保存图片": "save image",
    "复制链接": "copy link",
    "查看位置": "view location",
    "附近餐厅": "nearby restaurants",
    "预约成功": "booking successful",
    "修改地址": "change address",
    "上传文件": "upload file",
    "发送消息": "send message",
    "权限不足": "insufficient permission",
    "加载中": "loading",
    "请稍后": "please wait",
    "无法连接": "cannot connect",
    "已过期": "expired",
    "不支持": "not supported",
    "20点抢": "grab at 20:00",
    "外箱": "outer box",
    "木架": "wooden crate",
    "入仓费": "warehouse fee",
    "私人仓": "private warehouse",
    "国际运输": "intl shipping",
    "明显标签": "clear label",
    "贴上": "stick on",
    "包装费": "packaging fee",
    "出口": "exit/export",
    "加收": "extra charge",
    "新版洗面奶": "cleansing lotion",
}


@dataclass(frozen=True)
class CEDICTLookup:
    source: str
    pinyin: str
    english: str


@dataclass(frozen=True)
class Match:
    source: str
    label: str
    kind: str
    start: int
    end: int
    rank: int


@dataclass(frozen=True)
class LookupResult:
    original: str
    normalized: str
    phraseOverrideLabel: str | None
    ccCedictExactMatch: dict[str, object] | None
    ccCedictSegmentMatches: list[dict[str, object]]
    finalOverlayLabel: str | None
    finalSource: str


@dataclass(frozen=True)
class CoverageMetrics:
    totalPhrases: int
    phraseOverrideHits: int
    ccCedictExactHits: int
    ccCedictSegmentHits: int
    skipped: int
    dictionaryEntriesLoaded: int
    loadSeconds: float
    analyzeSeconds: float
    averageDisplayLabelLength: float
    maximumDisplayLabelLength: int
    labelsOver28Characters: int
    noisyLabelCount: int
    badLabelExamples: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Test a Quick Look-style Chinese-to-English dictionary pipeline "
            "using phrase rules first and CC-CEDICT fallback second."
        )
    )
    parser.add_argument(
        "cedict_sqlite",
        nargs="?",
        type=Path,
        help="Path to a CC-CEDICT SQLite DB generated by the dictionary tooling.",
    )
    parser.add_argument(
        "--cedict-db",
        type=Path,
        help="Path to a CC-CEDICT SQLite DB. Alias for the positional argument.",
    )
    parser.add_argument(
        "--phrases",
        help="Pipe-separated OCR phrases to test.",
    )
    parser.add_argument(
        "--terms-file",
        type=Path,
        help="Optional UTF-8 text file with one OCR phrase per line.",
    )
    parser.add_argument(
        "--phrases-file",
        type=Path,
        help="Alias for --terms-file. UTF-8 file with one OCR phrase per line.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON instead of human-readable output.",
    )
    return parser.parse_args()


def normalized_source(text: str) -> str:
    normalized = unicodedata.normalize("NFKC", text)
    normalized = normalized.replace("，", ",")
    invisible = {
        "\u200b",
        "\u200c",
        "\u200d",
        "\u2060",
        "\ufeff",
    }
    return "".join(
        character
        for character in normalized
        if character not in invisible and not character.isspace()
    )


def phrase_key(text: str) -> str:
    return re.sub(r"[,.。！？!?:：；;、\s]+", "", normalized_source(text))


def load_phrases(args: argparse.Namespace) -> list[str]:
    phrases_file = args.phrases_file or args.terms_file

    if phrases_file is not None:
        return [
            line.strip()
            for line in phrases_file.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

    if args.phrases:
        return [
            phrase.strip()
            for phrase in args.phrases.split("|")
            if phrase.strip()
        ]

    return DEFAULT_OCR_PHRASES


def load_cedict_entries(connection: sqlite3.Connection) -> dict[str, CEDICTLookup]:
    connection.row_factory = sqlite3.Row
    columns = {
        row["name"]
        for row in connection.execute("PRAGMA table_info(entries)").fetchall()
    }
    english_expression = (
        "COALESCE(NULLIF(englishDisplay, ''), NULLIF(englishRaw, ''), '')"
        if {"englishDisplay", "englishRaw"}.issubset(columns)
        else "english"
    )
    rows = connection.execute(
        f"""
        SELECT
            simplified,
            traditional,
            sourceCompact,
            pinyin,
            {english_expression} AS english
        FROM entries
        ORDER BY priority DESC, length(sourceCompact) DESC, simplified
        """
    ).fetchall()
    entries: dict[str, CEDICTLookup] = {}

    for row in rows:
        lookup = CEDICTLookup(
            source=row["simplified"],
            pinyin=row["pinyin"],
            english=row["english"],
        )

        for key in [
            row["simplified"],
            row["traditional"],
            row["sourceCompact"],
        ]:
            normalized_key = normalized_source(key or "")

            if normalized_key:
                entries.setdefault(normalized_key, lookup)

    return entries


def phrase_override_label(text: str) -> str | None:
    key = phrase_key(text)

    if key in PHRASE_OVERRIDES:
        return PHRASE_OVERRIDES[key]

    if match := re.fullmatch(r"([0-2]?\d)点抢", key):
        hour = int(match.group(1))

        if 0 <= hour <= 23:
            return f"grab at {hour:02d}:00"

    if match := re.fullmatch(r"暂无(数据|消息|内容)", key):
        noun = {
            "数据": "data",
            "消息": "messages",
            "内容": "content",
        }[match.group(1)]
        return f"no {noun}"

    if "网络错误" in key and "重试" in key:
        return "network error · retry"

    if match := re.fullmatch(r"支付(失败|成功)", key):
        status = "failed" if match.group(1) == "失败" else "successful"
        return f"payment {status}"

    if match := re.fullmatch(r"订单(已取消|已完成)", key):
        status = "canceled" if match.group(1) == "已取消" else "completed"
        return f"order {status}"

    if match := re.fullmatch(r"退款(处理中|成功|失败)", key):
        status = {
            "处理中": "processing",
            "成功": "successful",
            "失败": "failed",
        }[match.group(1)]
        return f"refund {status}"

    if re.fullmatch(r"(快递|物流)已发货", key):
        return "shipped"

    if re.fullmatch(r"退出.*登录", key):
        return "log out"

    if re.fullmatch(r"输入.*验证码", key):
        return "verification code"

    if match := re.fullmatch(r"(绑定|解绑).*手机号", key):
        return "bind phone" if match.group(1) == "绑定" else "unbind phone"

    return None


def exact_match(
    text: str,
    dictionary: dict[str, CEDICTLookup],
) -> Match | None:
    lookup = dictionary.get(text)

    if lookup is None:
        return None

    return Match(
        source=lookup.source,
        label=lookup.english,
        kind="cc_cedict_exact",
        start=0,
        end=len(text),
        rank=3,
    )


def find_segment_matches(
    text: str,
    dictionary: dict[str, CEDICTLookup],
) -> list[Match]:
    matches: list[Match] = []

    for source, lookup in dictionary.items():
        if not source or len(source) == 1:
            continue

        start = 0

        while True:
            index = text.find(source, start)

            if index == -1:
                break

            matches.append(
                Match(
                    source=source,
                    label=lookup.english,
                    kind="cc_cedict_segment",
                    start=index,
                    end=index + len(source),
                    rank=1,
                )
            )
            start = index + 1

    return matches


def select_non_overlapping(matches: list[Match], limit: int = 3) -> list[Match]:
    selected: list[Match] = []

    sorted_matches = sorted(
        matches,
        key=lambda match: (
            -match.rank,
            -(match.end - match.start),
            label_penalty(match.label),
            match.start,
            match.source,
        ),
    )

    for match in sorted_matches:
        if any(ranges_overlap(match, existing) for existing in selected):
            continue

        selected.append(match)

        if len(selected) == limit:
            break

    return sorted(selected, key=lambda match: match.start)


def label_penalty(label: str) -> int:
    penalty = len(label)

    if is_noisy_overlay_label(label):
        penalty += 100

    if len(label) > MAX_DISPLAY_LABEL_LENGTH:
        penalty += 30

    return penalty


def ranges_overlap(lhs: Match, rhs: Match) -> bool:
    return lhs.start < rhs.end and rhs.start < lhs.end


def compact_label(matches: list[Match]) -> str | None:
    labels = [match.label.strip() for match in matches if match.label.strip()]

    if not labels:
        return None

    selected: list[str] = []

    for label in labels[:3]:
        candidate = " · ".join([*selected, label])

        if len(candidate) <= MAX_DISPLAY_LABEL_LENGTH:
            selected.append(label)
        elif not selected:
            return label

    return " · ".join(selected) if selected else None


def analyze_phrase(
    phrase: str,
    cedict_entries: dict[str, CEDICTLookup],
) -> LookupResult:
    normalized = normalized_source(phrase)
    override_label = phrase_override_label(normalized)

    if override_label:
        return LookupResult(
            original=phrase,
            normalized=normalized,
            phraseOverrideLabel=override_label,
            ccCedictExactMatch=None,
            ccCedictSegmentMatches=[],
            finalOverlayLabel=override_label,
            finalSource="phrase_override",
        )

    exact = exact_match(normalized, cedict_entries)

    if exact is not None:
        return LookupResult(
            original=phrase,
            normalized=normalized,
            phraseOverrideLabel=None,
            ccCedictExactMatch=asdict(exact),
            ccCedictSegmentMatches=[],
            finalOverlayLabel=exact.label,
            finalSource="cc_cedict_exact",
        )

    selected_segments = select_non_overlapping(
        find_segment_matches(normalized, cedict_entries)
    )

    if selected_segments:
        return LookupResult(
            original=phrase,
            normalized=normalized,
            phraseOverrideLabel=None,
            ccCedictExactMatch=None,
            ccCedictSegmentMatches=[asdict(match) for match in selected_segments],
            finalOverlayLabel=compact_label(selected_segments),
            finalSource="cc_cedict_segment",
        )

    return LookupResult(
        original=phrase,
        normalized=normalized,
        phraseOverrideLabel=None,
        ccCedictExactMatch=None,
        ccCedictSegmentMatches=[],
        finalOverlayLabel=None,
        finalSource="skipped",
    )


def coverage_metrics(
    results: list[LookupResult],
    dictionary_entries_loaded: int,
    load_seconds: float,
    analyze_seconds: float,
) -> CoverageMetrics:
    labels = [
        result.finalOverlayLabel
        for result in results
        if result.finalOverlayLabel
    ]
    bad_examples = [
        label
        for label in labels
        if is_noisy_overlay_label(label) or len(label) > MAX_DISPLAY_LABEL_LENGTH
    ]

    return CoverageMetrics(
        totalPhrases=len(results),
        phraseOverrideHits=sum(
            result.finalSource == "phrase_override" for result in results
        ),
        ccCedictExactHits=sum(
            result.finalSource == "cc_cedict_exact" for result in results
        ),
        ccCedictSegmentHits=sum(
            result.finalSource == "cc_cedict_segment" for result in results
        ),
        skipped=sum(result.finalSource == "skipped" for result in results),
        dictionaryEntriesLoaded=dictionary_entries_loaded,
        loadSeconds=load_seconds,
        analyzeSeconds=analyze_seconds,
        averageDisplayLabelLength=(
            sum(len(label) for label in labels) / len(labels)
            if labels else 0.0
        ),
        maximumDisplayLabelLength=max((len(label) for label in labels), default=0),
        labelsOver28Characters=sum(
            len(label) > MAX_DISPLAY_LABEL_LENGTH for label in labels
        ),
        noisyLabelCount=sum(is_noisy_overlay_label(label) for label in labels),
        badLabelExamples=bad_examples[:8],
    )


def is_noisy_overlay_label(label: str) -> bool:
    lowercased = label.lower()
    noisy_fragments = [
        "variant of",
        "surname",
        "classifier",
        "literary",
        "dialect",
        "modal particle",
        "phonetic",
        "to touch briefly",
        "bound form",
        "abbr.",
    ]
    return any(fragment in lowercased for fragment in noisy_fragments)


def print_human(
    results: list[LookupResult],
    metrics: CoverageMetrics,
) -> None:
    print("Coverage summary")
    print("================")
    print(f"Total phrases: {metrics.totalPhrases}")
    print(f"Phrase override hits: {metrics.phraseOverrideHits}")
    print(f"CC-CEDICT exact hits: {metrics.ccCedictExactHits}")
    print(f"CC-CEDICT segment hits: {metrics.ccCedictSegmentHits}")
    print(f"Skipped: {metrics.skipped}")
    print(f"Dictionary entries loaded: {metrics.dictionaryEntriesLoaded}")
    print(f"Dictionary load seconds: {metrics.loadSeconds:.4f}")
    print(f"Analyze seconds: {metrics.analyzeSeconds:.4f}")
    print(f"Average display label length: {metrics.averageDisplayLabelLength:.1f}")
    print(f"Maximum display label length: {metrics.maximumDisplayLabelLength}")
    print(f"Labels over 28 characters: {metrics.labelsOver28Characters}")
    print(f"Noisy label count: {metrics.noisyLabelCount}")

    if metrics.badLabelExamples:
        print("Bad label examples:")
        for label in metrics.badLabelExamples:
            print(f"  - {label}")

    print()

    for result in results:
        print("=" * 72)
        print(f"OCR:        {result.original}")
        print(f"Normalized: {result.normalized}")

        if result.phraseOverrideLabel:
            print(f"Phrase override: {result.phraseOverrideLabel}")

        if result.ccCedictExactMatch:
            match = result.ccCedictExactMatch
            print(f"CC-CEDICT exact: {match['source']} -> {match['label']}")

        if result.ccCedictSegmentMatches:
            print("CC-CEDICT segments:")
            for match in result.ccCedictSegmentMatches:
                print(f"  - {match['source']} -> {match['label']}")

        if (
            not result.phraseOverrideLabel
            and not result.ccCedictExactMatch
            and not result.ccCedictSegmentMatches
        ):
            print("Matches: none")

        print(f"Final overlay: {result.finalOverlayLabel or 'SKIP'}")
        print(f"Final source:  {result.finalSource}")


def main() -> int:
    args = parse_args()
    cedict_sqlite = args.cedict_db or args.cedict_sqlite

    if cedict_sqlite is None:
        print(
            "CC-CEDICT SQLite DB is required as a positional argument or --cedict-db.",
            file=sys.stderr,
        )
        return 2

    if not cedict_sqlite.is_file():
        print(
            f"CC-CEDICT SQLite DB not found: {cedict_sqlite}",
            file=sys.stderr,
        )
        return 2

    load_start = time.perf_counter()
    connection = sqlite3.connect(cedict_sqlite)

    try:
        cedict_entries = load_cedict_entries(connection)
    finally:
        connection.close()

    load_seconds = time.perf_counter() - load_start
    phrases = load_phrases(args)
    analyze_start = time.perf_counter()
    results = [
        analyze_phrase(phrase, cedict_entries)
        for phrase in phrases
    ]
    analyze_seconds = time.perf_counter() - analyze_start
    metrics = coverage_metrics(
        results=results,
        dictionary_entries_loaded=len(cedict_entries),
        load_seconds=load_seconds,
        analyze_seconds=analyze_seconds,
    )

    if args.json:
        print(
            json.dumps(
                {
                    "metrics": asdict(metrics),
                    "results": [asdict(result) for result in results],
                },
                ensure_ascii=False,
                indent=2,
            )
        )
    else:
        print_human(results, metrics)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
