import Foundation

struct OverlayRenderResult: Equatable, Sendable {
    struct RenderMetadata: Equatable, Sendable {
        let generatedAt: Date
        let note: String

        static let placeholder = RenderMetadata(
            generatedAt: .now,
            note: "Placeholder overlay content generated by the initial scaffold."
        )
    }

    let sourceInput: ScreenshotInput
    let translatedBlocks: [TranslationBlock]
    let renderStyle: OverlayRenderStyle
    let renderMetadata: RenderMetadata
    let precomposedImageData: Data?

    static func placeholder(
        input: ScreenshotInput = .placeholder,
        style: OverlayRenderStyle = .defaultValue
    ) -> OverlayRenderResult {
        OverlayRenderResult(
            sourceInput: input,
            translatedBlocks: [
                TranslationBlock(
                    sourceText: "示例文本",
                    translatedText: "Пример перевода",
                    sourceBoundingBox: CGRect(x: 24, y: 40, width: 240, height: 56),
                    targetFrame: CGRect(x: 24, y: 40, width: 240, height: 72),
                    renderingStyle: style
                ),
                TranslationBlock(
                    sourceText: "立即购买",
                    translatedText: "Купить сейчас",
                    sourceBoundingBox: .init(x: 24, y: 120, width: 220, height: 50),
                    targetFrame: .init(x: 24, y: 120, width: 220, height: 70),
                    renderingStyle: style
                )
            ],
            renderStyle: style,
            renderMetadata: .placeholder,
            precomposedImageData: nil
        )
    }
}
